// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1kaBB6L-_0eHV1yMk0W1C27gq-9h_UeY',
    appId: '1:911784672095:android:5d4b8a024a6b81a47fd4ea',
    messagingSenderId: '911784672095',
    projectId: 'sisterly-840df',
    storageBucket: 'sisterly-840df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs-TB7RCGI95mDktHzh80ssADneUaR1Hc',
    appId: '1:911784672095:ios:3caa5b40af40f1857fd4ea',
    messagingSenderId: '911784672095',
    projectId: 'sisterly-840df',
    storageBucket: 'sisterly-840df.appspot.com',
    iosClientId: '911784672095-g6i0jqpqfevtpej75ammfd8hig4u2ifq.apps.googleusercontent.com',
    iosBundleId: 'com.sisterly.sisterly',
  );
}
